spring:
  application:
    name: organica
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/organica
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
